### ISSUE TITLE
Scrolling smoothness

### ISSUE THREAD

**Issue by ciwolsey** [carlosdcastillo/vim-mode#11]
When scrolling up it's smooth, but when scrolling down it appears quite.. laggy.. often skipping lines and jump all over the place.

**Comment by carlosdcastillo** [comment]
@ciwolsey It shouldn't jump all over the place. Try increasing the size (the height, mainly) of the Neovim window.

There will still be, however, some flickering.

**Comment by ciwolsey** [comment]
When nvim window is large it jumps around. If I shrink it to it's smallest parts of the text in atom don't redraw. It's like the size of the nvim window is affecting the size of the area I can see in atom.

**Comment by ciwolsey** [comment]
I made a video of the issues here: https://www.youtube.com/watch?v=VyuWkZX4m9E&feature=youtu.be

**Comment by carlosdcastillo** [comment]
@ciwolsey I see a couple of problems in the way your doing things which are a consequence of current limitations of neovim-mode:
- Once you start neovim-mode don't resize the Atom window, the number of columns is computed only once
- The number of rows of neovim (which in the video is 35) needs to be at least as large the number of columns of Atom (46 in the video)
