### ISSUE TITLE
Sync issues between Atom and nvim buffer

### ISSUE THREAD

**Issue by geoffharcourt** [carlosdcastillo/vim-mode#17]
![vim-mode-problem](https://cloud.githubusercontent.com/assets/319471/6881757/90d5c034-d543-11e4-8124-49ee20ede672.gif)

Using vim-mode at dd04fa461d3023759c49ec025789b7d77ef57f1a, Atom at 0.188.0, and Neovim at 0.0.0-alpha+201503281204.

I'm noticing issues like this where the contents of the line under the cursor look correct, but when you move the cursor away, the line's contents show something out of sync with the nvim buffer. The larger the file, the greater the number of sync problems.

Please let me know if there's any further information I can provide. This project looks awesome, and I'm very excited to see it advance.

**Comment by carlosdcastillo** [comment]
@geoffharcourt It seems like you have an exotic configuration of the line numbers. To sync up the location where the editing is being done neovim-mode uses the line numbers, it expects a fully normal, non-moving `set nu`. The way I test is by not having a .nvimrc and letting neovim-mode configure everything as needed.

**Comment by geoffharcourt** [comment]
Ah ha. I have relative line numbers except the current line set, which completely explains that.
