### ISSUE TITLE
dd command on the last line

### ISSUE THREAD

**Issue by adelarsq** [carlosdcastillo/vim-mode#19]
Amazing job. Now we have multiple cursors and minimap with Vim :clap: 

Since I don't have too much time I will try to help reporting some issues. Then let's go...

It's no possible delete the last line of a file with `dd` command.

**Comment by carlosdcastillo** [comment]
@adelarsq Thank you very much for posting all of these bugs. Keep your bug reports coming.

Yes, I am able to reproduce that dd does not eliminate the last line. I will troubleshoot and fix over the week end.

**Comment by carlosdcastillo** [comment]
@adelarsq I think I solved this one. Can you please pull the latest changes and check if it works for you? Thanks!

**Comment by adelarsq** [comment]
Good job!
Since I did an update on Atom for the last version (0.190) I have some issues with the plugin. The editor are creating more and more tabs each time that I press any key. With time I will try to go back on the 0.184 version.
I think that the request can be closed for now.

**Comment by gaving** [comment]
@carlosdcastillo :+1: Latest from master sorts this for me.
