### ISSUE TITLE
J don't work with multiple cursors

### ISSUE THREAD

**Issue by adelarsq** [carlosdcastillo/vim-mode#20]
Let's put the cursor on the lines 1, 3 and 5 from this file:

```
1
2
3
4
5
6
```

After the J command the file looks like:

```
1
2
3 4
5 6
```

**Comment by carlosdcastillo** [comment]
One day this will work. Right now there is no expectation that any multiple cursor transaction will do anything reasonable.

BTW how do you add multiple cursors to Atom?

**Comment by adelarsq** [comment]
I pressed Ctrl+MouseRight and than I tried some Vim commands. Some work perfectly :smile: 

I think that multiple cursors are just an extension from the visual block mode. May be possible to implement these two together.

**Comment by adelarsq** [comment]
Closing old issue.
