### ISSUE TITLE
ggVG when last line of a file is empty

### ISSUE THREAD

**Issue by adelarsq** [carlosdcastillo/vim-mode#21]
`ggVG` does not show the selection on the last line when it is empty.

I don't know if it's a bug or not. Since I find strange I opened an issue.

**Comment by carlosdcastillo** [comment]
This one I don't think I'm able to reproduce. How do you know a line is selected or not?

**Comment by adelarsq** [comment]
On Vim exists a visual indication that the last line is selected:

![image](https://cloud.githubusercontent.com/assets/430272/7012872/ca02398e-dc8a-11e4-8311-0e3f1a5fd02f.png)

On Atom don't exists a visual indication that the last line is selected or not (just for the 1, 2 and 3 lines):

![image](https://cloud.githubusercontent.com/assets/430272/7012885/12471dc2-dc8b-11e4-8a45-c4de95aa09f9.png)

I don't know if this is a limitation from the editor or not. Same thing occurs without vim-mode. Is it possible to change this behavior?

**Comment by adelarsq** [comment]
Closing old issue. I wasn't able to reproduce.
