### ISSUE TITLE
onDidChangeScrollTop error on launch

### ISSUE THREAD

**Issue by gaving** [carlosdcastillo/vim-mode#22]
First off, thanks for the awesome project.

On launching Atom I get the below error, though things seem fine when the error is dismissed.

Figured I'd post it in case it helped.

**Atom Version**: 0.196.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [vim-mode](https://github.com/carlosdcastillo/vim-mode) package, v0.10.1
### Stack Trace

Uncaught TypeError: Cannot read property 'onDidChangeScrollTop' of undefined

```
At /C:/Users/gavin/.atom/packages/vim-mode/lib/vim-state.coffee:609

TypeError: Cannot read property 'onDidChangeScrollTop' of undefined
    at /C:/Users/gavin/.atom/packages/vim-mode/lib/vim-state.coffee:609:60
    at Socket.<anonymous> (/C:/Users/gavin/.atom/packages/vim-mode/lib/vim-state.coffee:118:13)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:109:10)
    at Pipe.onread (net.js:517:20)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
vim-mode, v0.10.1

# Dev
No dev packages
```

**Comment by carlosdcastillo** [comment]
I think I just pushed changes so that this doesn't happen again. Let me know if it solves it for you.

**Comment by gaving** [comment]
@carlosdcastillo :+1: That sorts it, cheers!
