### ISSUE TITLE
Problem with installing vim-mode on Windows 7

### ISSUE THREAD

**Issue by Stianhn** [carlosdcastillo/vim-mode#33]
apm install # install dependencies
Installing # to C:\Users\myUser.atom\packages
TypeError: Cannot read property 'latest' of undefined

**Comment by carlosdcastillo** [comment]
Just found my Windows 8 laptop. And tried that with the most recent version and I did not get that error. It said "Installing modules" the text appeared "done" appeared.

Also I did a 5 minute sanity check of the current situation on Windows and it seems to be working surprisingly well given that I try it on Windows once every 6 months.

**Comment by Stianhn** [comment]
My mistake. I wasn't able to interpret "# install dependencies" as a comment, and neither was my non-bash shell. When I removed it the command worked.
