### ISSUE TITLE
Improve setup instructions.

### ISSUE THREAD

**Issue by jordwalke** [carlosdcastillo/vim-mode#5]
I think this could get a bunch of more attention/help if you would cover some step by step instructions on setting up neovim/Atom/vim-mode.

I think your approach is definitely a great way to ensure that vim diehards have a great editing experience in Atom.

**Comment by carlosdcastillo** [comment]
I'll try to prepare installation instructions. I think that the plugin was so raw before that it did not make sense. But now it is starting to be usable. I try to use it for most my editing.

**Comment by jordwalke** [comment]
Sounds great, thank you.
