### ISSUE TITLE
Is Vim Completion supported?

### ISSUE THREAD

**Issue by jordwalke** [carlosdcastillo/vim-mode#6]
If I have Vim completion plugins, will this branch of `vim-mode` (eventually) allow reusing those Vim plugins? Are the popup menu options/interactions communicated back and forth between NeoVim/Atom?

**Comment by carlosdcastillo** [comment]
It does work. I just tried pressing Ctrl-N and it completed with different options. The UI connection is not done (it does not present a code completion Atom widget) all it does is overlay the text on the Atom window, but it worked.

**Comment by jordwalke** [comment]
Cool. That sounds like a great start (especially if it can either match the color scheme from Vim or possibly Atom's). BTW: Is it your goal to have the color scheme of Vim be reflected, or Atom's? I can see either being nice/useful.
